on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

concurrency:
  # Cancel in-progress jobs for pull requests but not for main branch runs.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Lint (clippy)
        run: cargo clippy --workspace --all-features --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt --check
      - name: Check for differences
        run: git diff --exit-code

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # 1.48 is the MSRV.
        rust-version:
          - "1.48"
          - stable
        exclude:
          # This version fails with "archive member 'lib.rmeta' with length xxxxx is not
          # mach-o or llvm bitcode file".
          - os: macos-latest
            rust-version: "1.48"
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      # Use the Git CLI to do fetches -- apparently there's something wrong with the version of
      # libgit2 shipped with Rust 1.44. This fixes that.
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Build the library
        run: cargo build
      - name: Test
        run: cargo test
