on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

concurrency:
  # Cancel in-progress jobs for pull requests but not for main branch runs.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install just, cargo-hack, and cargo-sync-rdme
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-hack,cargo-sync-rdme
      - name: Lint (clippy)
        run: just powerset clippy --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt
      - name: Run rustdoc
        run: just rustdoc
        env:
          RUSTDOCFLAGS: -Dwarnings
      - name: Install nightly toolchain for cargo-sync-rdme
        uses: dtolnay/rust-toolchain@nightly
      - name: Regenerate readmes
        run: just generate-readmes
      - name: Check for differences
        run: git diff --exit-code

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # 1.74 is the MSRV.
        rust-version:
          - "1.74"
          - stable
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      # Use the Git CLI to do fetches -- apparently there's something wrong with the version of
      # libgit2 shipped with Rust 1.44. This fixes that.
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-hack,nextest
      - name: Build
        run: just powerset build
      - name: Run tests
        run: just powerset nextest run
      - name: Doctests
        run: just powerset test --doc
