on:
  push:
    branches:
      - main

name: Docs

jobs:
  build-docs:
    name: Build and deploy documentation
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build rustdoc
        env:
          RUSTC_BOOTSTRAP: 1
          RUSTDOCFLAGS: -Dwarnings --cfg=doc_cfg
        run: just rustdoc --workspace
      - name: Organize
        run: |
          rm -rf target/gh-pages
          mkdir target/gh-pages
          mv target/doc target/gh-pages/rustdoc
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: target/gh-pages
    
  deploy-docs:
    name: Deploy documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
